const PDFDocument = require('pdfkit');
const { stringify } = require('csv-stringify/sync');
const pool = require('../config/database');

const generatePDFReport = async (userId, goalId) => {
  try {
    if (!userId || !goalId) {
      return {
        success: false,
        error: 'userId and goalId are required'
      };
    }

    const goalResult = await pool.query(
      'SELECT * FROM goals WHERE id = $1 AND user_id = $2',
      [goalId, userId]
    );

    if (goalResult.rows.length === 0) {
      return {
        success: false,
        error: 'Goal not found'
      };
    }

    const goal = goalResult.rows[0];

    const milestonesResult = await pool.query(
      'SELECT * FROM milestones WHERE goal_id = $1 ORDER BY start_date ASC',
      [goalId]
    );

    const tasksResult = await pool.query(
      'SELECT * FROM tasks WHERE goal_id = $1 ORDER BY due_date ASC',
      [goalId]
    );

    const topicsResult = await pool.query(
      'SELECT * FROM topics WHERE goal_id = $1 ORDER BY confidence DESC',
      [goalId]
    );

    const doc = new PDFDocument({
      size: 'A4',
      margin: 50
    });

    doc.fontSize(24).font('Helvetica-Bold').text('Goal Progress Report', 50, 50);
    doc.fontSize(12).font('Helvetica').text(`Generated on ${new Date().toLocaleDateString()}`, 50, 80);
    doc.moveDown();

    doc.fontSize(16).font('Helvetica-Bold').text('Goal Summary', { underline: true });
    doc.fontSize(11).font('Helvetica');
    doc.text(`Name: ${goal.name}`);
    doc.text(`Status: ${goal.status}`);
    doc.text(`Progress: ${goal.progress}%`);
    doc.text(`Difficulty: ${goal.difficulty}`);
    doc.text(`Deadline: ${new Date(goal.deadline).toLocaleDateString()}`);
    doc.text(`Hours per Week: ${goal.time_per_week}`);
    doc.moveDown();

    if (milestonesResult.rows.length > 0) {
      doc.fontSize(16).font('Helvetica-Bold').text('Milestones', { underline: true });
      milestonesResult.rows.forEach((milestone, index) => {
        doc.fontSize(11).font('Helvetica-Bold').text(`${index + 1}. ${milestone.name}`);
        doc.fontSize(10).font('Helvetica');
        doc.text(`  Start: ${new Date(milestone.start_date).toLocaleDateString()}`);
        doc.text(`  End: ${new Date(milestone.end_date).toLocaleDateString()}`);
        doc.text(`  Status: ${milestone.completed ? 'Completed ✓' : 'In Progress'}`);
      });
      doc.moveDown();
    }

    if (topicsResult.rows.length > 0) {
      doc.fontSize(16).font('Helvetica-Bold').text('Topic Confidence', { underline: true });
      topicsResult.rows.forEach(topic => {
        const level = topic.confidence >= 80 ? 'Expert' :
                     topic.confidence >= 60 ? 'Proficient' :
                     topic.confidence >= 40 ? 'Intermediate' :
                     topic.confidence >= 20 ? 'Beginner' : 'Learning';
        doc.fontSize(11).font('Helvetica');
        doc.text(`${topic.name}: ${topic.confidence}% (${level})`);
      });
      doc.moveDown();
    }

    const completedTasks = tasksResult.rows.filter(t => t.completed).length;
    doc.fontSize(16).font('Helvetica-Bold').text('Tasks Summary', { underline: true });
    doc.fontSize(11).font('Helvetica');
    doc.text(`Total Tasks: ${tasksResult.rows.length}`);
    doc.text(`Completed: ${completedTasks}`);
    doc.text(`Remaining: ${tasksResult.rows.length - completedTasks}`);
    doc.moveDown();

    doc.fontSize(9).font('Helvetica').text('This report was generated by Goal Planner', 50, doc.page.height - 50, { align: 'center' });

    return {
      success: true,
      doc: doc,
      filename: `goal_report_${goalId}_${Date.now()}.pdf`
    };

  } catch (error) {
    console.error('Generate PDF error:', error);
    return {
      success: false,
      error: 'Failed to generate PDF'
    };
  }
};

const generateCSVExport = async (userId) => {
  try {
    if (!userId) {
      return {
        success: false,
        error: 'userId is required'
      };
    }

    const goalsResult = await pool.query(
      'SELECT id, name, progress, status, deadline, difficulty FROM goals WHERE user_id = $1 ORDER BY created_at DESC',
      [userId]
    );

    const csvData = goalsResult.rows.map(goal => ({
      'Goal Name': goal.name,
      'Progress': `${goal.progress}%`,
      'Status': goal.status,
      'Difficulty': goal.difficulty,
      'Deadline': new Date(goal.deadline).toLocaleDateString(),
      'Goal ID': goal.id
    }));

    const csv = stringify(csvData, {
      header: true
    });

    return {
      success: true,
      csv: csv,
      filename: `goals_export_${Date.now()}.csv`
    };

  } catch (error) {
    console.error('Generate CSV error:', error);
    return {
      success: false,
      error: 'Failed to generate CSV'
    };
  }
};

const getCalendarEvents = async (userId, goalId) => {
  try {
    if (!userId || !goalId) {
      return {
        success: false,
        error: 'userId and goalId are required'
      };
    }

    const goalResult = await pool.query(
      'SELECT * FROM goals WHERE id = $1 AND user_id = $2',
      [goalId, userId]
    );

    if (goalResult.rows.length === 0) {
      return {
        success: false,
        error: 'Goal not found'
      };
    }

    const goal = goalResult.rows[0];

    const tasksResult = await pool.query(
      'SELECT * FROM tasks WHERE goal_id = $1 ORDER BY due_date ASC',
      [goalId]
    );

    let ical = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Goal Planner//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:goal-${goalId}@goalplanner.com
DTSTAMP:${new Date().toISOString().replace(/[-:]/g, '').split('.')[0]}Z
SUMMARY:${goal.name}
DESCRIPTION:Goal deadline for ${goal.name}
DTSTART:${new Date(goal.deadline).toISOString().replace(/[-:]/g, '').split('.')[0]}Z
DTEND:${new Date(goal.deadline).toISOString().replace(/[-:]/g, '').split('.')[0]}Z
END:VEVENT
`;

    tasksResult.rows.forEach(task => {
      ical += `BEGIN:VEVENT
UID:task-${task.id}@goalplanner.com
DTSTAMP:${new Date().toISOString().replace(/[-:]/g, '').split('.')[0]}Z
SUMMARY:${task.name}
DESCRIPTION:Task for goal: ${goal.name}
DTSTART:${new Date(task.due_date).toISOString().replace(/[-:]/g, '').split('.')[0]}Z
DTEND:${new Date(task.due_date).toISOString().replace(/[-:]/g, '').split('.')[0]}Z
STATUS:${task.completed ? 'COMPLETED' : 'IN-PROCESS'}
END:VEVENT
`;
    });

    ical += `END:VCALENDAR`;

    return {
      success: true,
      ical: ical,
      filename: `goal_calendar_${goalId}_${Date.now()}.ics`
    };

  } catch (error) {
    console.error('Get calendar events error:', error);
    return {
      success: false,
      error: 'Failed to generate calendar events'
    };
  }
};

module.exports = { generatePDFReport, generateCSVExport, getCalendarEvents };